/**
 * Poster stills per scene (one frame from the footage) and a pre-blurred, darkened backdrop for
 * panels that sit over artwork. Generated by tools/ui/make-posters.sh from the scene footage.
 */

import type { ImageSourcePropType } from "react-native";

const POSTERS: Record<string, ImageSourcePropType> = {
  "tos-bridge": require("../assets/posters/tos-bridge.jpg"),
  "tos-lab": require("../assets/posters/tos-lab.jpg"),
  "the-envelope": require("../assets/posters/the-envelope.jpg"),
  "micro-scene-a": require("../assets/posters/micro-scene-a.jpg"),
  "micro-scene-b": require("../assets/posters/micro-scene-b.jpg"),
  prototype: require("../assets/posters/prototype.jpg"),
};
const BACKDROPS: Record<string, ImageSourcePropType> = {
  "tos-bridge": require("../assets/posters/backdrop-tos-bridge.jpg"),
  "tos-lab": require("../assets/posters/backdrop-tos-lab.jpg"),
  "the-envelope": require("../assets/posters/backdrop-the-envelope.jpg"),
  "micro-scene-a": require("../assets/posters/backdrop-micro-scene-a.jpg"),
  "micro-scene-b": require("../assets/posters/backdrop-micro-scene-b.jpg"),
  prototype: require("../assets/posters/backdrop-prototype.jpg"),
};

/** Fixture scenes share the clock-test footage. */
function key(sceneId: string): string { return sceneId.startsWith("fixture-") ? "prototype" : sceneId; }
export function posterFor(sceneId: string): ImageSourcePropType { return POSTERS[key(sceneId)] ?? POSTERS.prototype; }
export function backdropFor(sceneId: string): ImageSourcePropType { return BACKDROPS[key(sceneId)] ?? BACKDROPS.prototype; }
