#!/usr/bin/env node --experimental-strip-types
/**
 * Bundle scene caption assets into the Vega app as TypeScript modules.
 *
 *   npm run bundle-assets
 *
 * For every directory under assets/ that contains captions.en.vtt, this validates the track and
 * optional companion.en.json, then writes apps/vega-player/src/assets/scenes.generated.ts with
 * the VTT text and the companion JSON inlined. The app reads captions from that module so the
 * demo has no network dependency for captions (the VVD cannot read arbitrary files at runtime
 * without packaging them, and packaged raw assets are read via fetch(file:///pkg/assets/raw/...)).
 *
 * Validation failures stop the bundle: the app must never ship a companion file that fails.
 */

import { readdirSync, readFileSync, statSync, writeFileSync, existsSync, mkdirSync } from "node:fs";
import { join } from "node:path";
import { parseVtt, validateProfile, formatValidation } from "../packages/core/src/index.ts";

const ROOT = new URL("..", import.meta.url).pathname;
const ASSETS = join(ROOT, "assets");
const OUT = join(ROOT, "apps/vega-player/src/assets/scenes.generated.ts");

type Bundle = { id: string; vtt: string; companion: unknown | null; companionFile?: string };
const bundles: Bundle[] = [];
let failed = false;

for (const dir of readdirSync(ASSETS)) {
  const p = join(ASSETS, dir);
  if (!statSync(p).isDirectory()) continue;
  const vttPath = join(p, "captions.en.vtt");
  if (!existsSync(vttPath)) continue;
  const vtt = readFileSync(vttPath, "utf8");
  const parsed = parseVtt(vtt);
  parsed.warnings.forEach((w) => console.log(`warning  ${dir}/captions.en.vtt: ${w}`));
  let companion: unknown | null = null;
  let companionFile: string | undefined;
  for (const name of ["companion.en.json", "sightline.en.json"]) {
    const cp = join(p, name);
    if (existsSync(cp)) {
      companionFile = name;
      try { companion = JSON.parse(readFileSync(cp, "utf8")); } catch (e) { console.log(`error    ${dir}/${name}: invalid JSON (${String(e)})`); failed = true; break; }
      const r = validateProfile(companion, parsed.cues);
      console.log(`${dir}/${name}:\n${formatValidation(r)}`);
      // Cue-level errors are allowed only for fixture scenes (they exist to exercise per-cue fallback on
      // the device); structural errors, or any error in a real scene, stop the bundle.
      const cueLevelOnly = r.errors.every((e) => e.path.startsWith("$.cues."));
      if (!r.ok && !(dir.startsWith("fixture-") && cueLevelOnly)) failed = true;
      else if (!r.ok) console.log(`note: ${dir} is a fixture; cue-level errors are bundled on purpose`);
      break;
    }
  }
  bundles.push({ id: dir, vtt, companion, companionFile });
  console.log(`bundled ${dir}: ${parsed.cues.length} cues${companionFile ? ` + ${companionFile}` : " (no companion file)"}`);
}

if (failed) { console.error("bundle aborted: fix validation errors first"); process.exit(1); }

mkdirSync(join(ROOT, "apps/vega-player/src/assets"), { recursive: true });
const body = `/* AUTO-GENERATED by tools/bundle-assets.ts. Do not edit; edit assets/<scene>/ and re-run npm run bundle-assets. */

export type BundledScene = { id: string; vtt: string; companion: unknown | null; companionFile?: string };

export const SCENES_BUNDLED: Record<string, BundledScene> = ${JSON.stringify(Object.fromEntries(bundles.map((b) => [b.id, b])), null, 2)};
`;
writeFileSync(OUT, body);
console.log(`wrote ${OUT} (${bundles.length} scene${bundles.length === 1 ? "" : "s"})`);
